[package]
name = "ky"
description = "Simple password manager written in rust"
version = "0.0.1"
authors = ["numtostr <vikasraj1911@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.16.0", default-features = false, features = ["zstd"] }
thiserror = "1.0.25"
clap = { git = "https://github.com/clap-rs/clap", rev = "24f5cd6" }
dialoguer = "0.8.0"
argon2 = "0.2.1"
rand = { version = "0.8.3", features = ["std"] }
aes-gcm-siv = "0.10.0"
sha2 = "0.9.5"
hex = "0.4.3"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
