[package]
name = "lok"
version = "0.1.0"
authors = ["numtostr <vikasraj1911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.16.0", default-features = false, features = ["lz4"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
