[package]
name = "ky"
description = "Simple password manager written in rust"
version = "0.0.1"
authors = ["numtostr <vikasraj1911@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocksdb = { version = "0.16.0", default-features = false, features = ["lz4"] }
thiserror = "1.0.25"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
