[alias]
b = "build --release"
ii = "install --path . --offline"

[target.'cfg(unix)']
rustflags = ["-C", "link-arg=-s"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
