name: pull_request

on:
    pull_request:
        paths-ignore:
            - "LICENSE"
            - "Makefile"
            - "README.md"
        branches:
            - master

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        name: Review
        strategy:
            matrix:
                job:
                    - {
                          os: ubuntu-latest,
                          target: aarch64-unknown-linux-gnu,
                          use_cross: true,
                      }
                    - {
                          os: ubuntu-latest,
                          target: armv7-unknown-linux-gnueabihf,
                          use_cross: true,
                      }
                    - {
                          os: ubuntu-latest,
                          target: x86_64-unknown-linux-gnu,
                          use_cross: false,
                      }
                    # - {
                    #       os: windows-latest,
                    #       target: x86_64-pc-windows-msvc,
                    #       use_cross: false,
                    #   }
                    - {
                          os: macos-latest,
                          target: x86_64-apple-darwin,
                          use_cross: false,
                      }
        runs-on: ${{ matrix.job.os }}
        timeout-minutes: 20
        steps:
            - name: Git Checkout
              uses: actions/checkout@v2

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.job.target }}
                  override: true
                  profile: minimal

            - name: Test
              uses: actions-rs/cargo@v1
              with:
                  use-cross: ${{ matrix.job.use_cross }}
                  command: test
                  args: --target=${{ matrix.job.target }}

            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  use-cross: ${{ matrix.job.use_cross }}
                  command: build
                  args: --release --target=${{ matrix.job.target }}
